services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"

# Note we don't need to define the 'network'.
# Different services (in our case 'pgdatabase' and 'pgadmin') becomes part of the same network automatically.

# Stop any container running that are configured in the compose file (check by 'docker ps')
#   docker stop <container id> or docker stop <container name>

# Then execute >> docker compose up -d 
# -d is for the detached mode 

# To stop >> "docker compose down"